import json
import logging
import re
from typing import Dict, Any, List, Generator
from openai import OpenAI
from app.config import settings

logger = logging.getLogger(__name__)

# Initialize client
def get_openai_client():
    if settings.OPENAI_DISABLED:
        return None
    if settings.GEMINI_API_KEY:
        return OpenAI(api_key=settings.GEMINI_API_KEY, base_url=settings.GEMINI_BASE_URL)
    if settings.OPENAI_API_KEY:
        return OpenAI(api_key=settings.OPENAI_API_KEY)
    return None

def get_model_name():
    if settings.GEMINI_API_KEY:
        return settings.GEMINI_MODEL_NAME
    return settings.OPENAI_MODEL_NAME


def analyze_agreement_instant(raw_text: str) -> Dict[str, Any]:
    """
    Runs an initial, deep structured analysis on the agreement text.
    Extracts summary, permissions, ownership, AI training rights, cancellation, and key clauses.
    """
    client = get_openai_client()
    
    if not client:
        # Mock structured output if API key is missing, for easier demo out-of-the-box
        return get_mock_analysis_response(raw_text[:200])
        
    prompt = f"""
    You are an expert legal agreement interpreter. Your role is to analyze the following agreement text and convert it into a highly structured, plain-English summary.
    
    CRITICAL INSTRUCTIONS:
    - Remain completely neutral and objective.
    - DO NOT give legal advice or make recommendations.
    - DO NOT assign risk scores or safety ratings.
    - Explicitly state if a clause is ambiguous or if details are missing.
    - Pay extra attention to AI model training rights, uploaded content ownership, and data retention.
    
    Return your analysis strictly as a JSON object with the following structure:
    {{
        "summary": "A concise paragraph summarizing the entire agreement.",
        "category": "Terms of Service | Privacy Policy | EULA | AI Agreement | SaaS Agreement | Consent Form",
        "ai_training": "Summary of terms regarding AI training, model optimization, prompt ownership, and generated content ownership. State if model training is permitted.",
        "permissions": "What permissions or licenses does the user grant the provider (e.g., global license to content, telemetry)?",
        "ownership": "Who owns uploaded data, files, prompts, and output content generated by the service?",
        "termination": "What are the rules regarding contract cancellation, termination by provider, and refund terms?",
        "retention": "How long is user data stored? What are deletion terms?",
        "key_clauses": [
            {{
                "topic": "Topic category",
                "clause_title": "Descriptive title of the clause",
                "original_snippet": "Actual relevant sentence or short quote from the agreement (must match exact text if possible)",
                "plain_english": "Clear, grounded explanation in simple terms.",
                "status": "clear | ambiguous"
            }}
        ]
    }}
    
    Agreement text:
    {raw_text[:12000]}  # Truncate to fit token limits safely
    """
    
    try:
        response = client.chat.completions.create(
            model=get_model_name(),
            messages=[
                {"role": "system", "content": "You are a professional legal agreement analyzer. Return only valid JSON."},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.2
        )
        result_str = response.choices[0].message.content
        return json.loads(result_str)
    except Exception as e:
        logger.error(f"Error calling OpenAI for instant analysis: {e}")
        if "quota" in str(e).lower() or "429" in str(e):
            settings.OPENAI_DISABLED = True
            logger.warning("OpenAI quota exceeded. Instantly falling back to offline demonstration analysis.")
            return get_mock_analysis_response(raw_text[:200])
        return {
            "error": "Failed to analyze document. Please check your OpenAI API key or network connection.",
            "details": str(e)
        }


def explain_clause_in_mode(clause_text: str, mode: str) -> Dict[str, Any]:
    """
    Translates a specific selected clause snippet into one of the four explanation styles:
    Simple, Teen-Friendly, Technical, Legal Style.
    """
    client = get_openai_client()
    
    if not client:
        return {
            "explanation": f"[API Key Missing] Mock explanation of: \"{clause_text[:60]}...\" in style '{mode}'. To enable, configure OPENAI_API_KEY.",
            "mode": mode,
            "grounded": True
        }
        
    style_instructions = {
        "Simple": "Explain in plain English at an 8th-grade reading level. Keep paragraphs short and avoid jargon.",
        "Teen-Friendly": "Explain using modern, conversational language that a teenager would easily understand. Use analogies and light-hearted tones, but remain accurate.",
        "Technical": "Explain with focus on data architecture, security measures, telemetry collection, API policies, and code usage. Maintain high technical precision.",
        "Legal": "Explain the precise legal consequences, focusing on liability limits, indemnification, dispute resolution, governing law, and user waivers. Keep the language direct and clear."
    }
    
    instruction = style_instructions.get(mode, style_instructions["Simple"])
    
    prompt = f"""
    You are an AI agreement interpreter. Translate the following clause into a plain-English explanation.
    
    Style requested: {mode} ({instruction})
    
    Rules:
    - Rely ONLY on the provided clause. Do not assume facts outside the text.
    - If the clause is vague, ambiguous, or lacks context, explicitly state: "This clause is ambiguous" or "The phrasing is unclear".
    - Remain neutral. Do NOT give legal advice. Do NOT say 'this is safe' or 'avoid this'.
    
    Clause to explain:
    "{clause_text}"
    
    Output format:
    Return a JSON object with:
    {{
        "explanation": "Your explanation text here.",
        "ambiguity_noted": true/false
    }}
    """
    
    try:
        response = client.chat.completions.create(
            model=get_model_name(),
            messages=[
                {"role": "system", "content": "You are a professional clause interpreter. Return JSON."},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.3
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        logger.error(f"Error explaining clause: {e}")
        if "quota" in str(e).lower() or "429" in str(e):
            settings.OPENAI_DISABLED = True
            logger.warning("OpenAI quota exceeded. Falling back to offline mock explanation.")
        return {
            "explanation": f"[Quota Exceeded] Mock explanation of: \"{clause_text[:60]}...\" in style '{mode}'. Please update your OpenAI billing details.",
            "ambiguity_noted": False
        }


def stream_grounded_chat(query: str, chat_history: List[Dict[str, str]], context_chunks: List[Dict[str, Any]]) -> Generator[str, None, None]:
    """
    Streams a chat response grounded in retrieved document chunks.
    Injects source citations and highlights ambiguity.
    """
    client = get_openai_client()
    
    # 1. Format retrieved chunks as structured context
    context_str = ""
    for idx, chunk in enumerate(context_chunks):
        context_str += f"--- SOURCE BLOCK {idx + 1} (Chunk ID: {chunk['chunk_index']}) ---\n"
        context_str += f"{chunk['content']}\n\n"
        
    system_prompt = f"""
    You are "TnC Bot", a helpful, professional, and friendly AI agreement interpretation assistant.
    Your role is to help the user understand terms, conditions, privacy policies, and contracts they upload, and answer general questions about contracts or chat normally.
    
    CONVERSATIONAL RULES:
    - For general greetings, chit-chat, or introductions (e.g., "hi", "hello", "how are you", "who are you"), reply naturally and introduce yourself as TnC Bot.
    
    GROUNDING & ACCURACY (When the user asks about the uploaded document):
    - Answer using the provided SOURCE BLOCKS below whenever possible.
    - Refer to specific source blocks using citations in the format `[Block 1]` or `[Block 2]` when citing facts from the agreement.
    - If the user asks a question about the document that is NOT covered in the source blocks, politely state that you cannot find this in the document, but you can offer a general explanation based on standard contract terms if helpful.
    - Keep answers friendly, clear, and easy to understand.
    - DO NOT offer professional legal advice.
    
    SOURCE BLOCKS:
    {context_str}
    """
    
    messages = [{"role": "system", "content": system_prompt}]
    
    # Add conversation history
    for msg in chat_history[-6:]:  # Keep last 6 exchanges for context
        messages.append({"role": msg["role"], "content": msg["content"]})
        
    messages.append({"role": "user", "content": query})
    
    if not client:
        # Mock streaming response
        mock_resp = f"**[API KEY MISSING - MOCK ANSWER]**\nBased on your question: *\"{query}\"*, I would retrieve matching clauses from your document.\n\nHere is what I found:\n- **AI Model usage**: If this is an AI tool, standard policies usually claim ownership over prompts but grant you generated outputs. However, they may retain the right to train their models on your files unless you opt out.\n- **Data sharing**: Providers commonly share data with sub-processors.\n\n*Please set your `OPENAI_API_KEY` in the `.env` file to enable real grounded answers.*"
        for word in mock_resp.split(" "):
            yield word + " "
        return

    try:
        response = client.chat.completions.create(
            model=get_model_name(),
            messages=messages,
            stream=True,
            temperature=0.3
        )
        for chunk in response:
            content = chunk.choices[0].delta.content
            if content:
                yield content
    except Exception as e:
        logger.error(f"Error in streaming chat: {e}")
        if "quota" in str(e).lower() or "429" in str(e):
            settings.OPENAI_DISABLED = True
            logger.warning("OpenAI quota exceeded during chat. Falling back to offline assistant mode.")
        yield f"\n[OpenAI Quota Exceeded. Grounded answers disabled. Error: {str(e)}]\n"


# Mock helper
def get_mock_analysis_response(sample_text: str) -> Dict[str, Any]:
    return {
        "summary": "This is a demonstration summary. To enable actual document analysis, please add a valid OPENAI_API_KEY to your backend's .env file. TnC Bot parses, structures, and simplifies digital contracts.",
        "category": "AI Agreement",
        "ai_training": "Standard terms indicate that the provider may train their machine learning models on inputs (prompts, uploaded files) unless you explicitly opt out in the accounts panel. Output content is typically owned by the user, but templates or system generations remain company property.",
        "permissions": "You grant the company a worldwide, royalty-free license to host, store, run, reproduce, process, adapt, modify, publish, and translate your uploaded content for product operation and maintenance.",
        "ownership": "User retains copyright and ownership of the original prompts and documents uploaded. The provider owns the platform software, logos, templates, and pre-built codebases.",
        "termination": "The provider reserves the right to terminate accounts immediately for breach of terms. Subscription fees are generally non-refundable unless required by local consumer protection laws.",
        "retention": "Service data is retained for as long as your account is active, or for up to 30 days after deletion request. Telemetry logs may be kept indefinitely in anonymized forms.",
        "key_clauses": [
            {
                "topic": "AI Training",
                "clause_title": "Model Training Consent",
                "original_snippet": "We may use content submitted to improve our machine learning models and services.",
                "plain_english": "The provider can use your prompts and uploaded files to train their AI models.",
                "status": "clear"
            },
            {
                "topic": "Arbitration",
                "clause_title": "Class Action Waiver",
                "original_snippet": "Any disputes must be resolved on an individual basis through binding arbitration, waiving class actions.",
                "plain_english": "You agree not to sue the company in a group lawsuit. All disputes will be decided by an individual arbitrator.",
                "status": "clear"
            },
            {
                "topic": "Data Retention",
                "clause_title": "Account Deletion Lag",
                "original_snippet": "Residual copies of deleted account data may persist in backup systems for a commercially reasonable period.",
                "plain_english": "When you delete your account, your data might remain on backup servers for an unspecified time.",
                "status": "ambiguous"
            }
        ]
    }
